### ISSUE TITLE
No module named 'v4l2ctl.utils'

### ISSUE THREAD

**Issue by Williangalvani** [MichaelIsrael/v4l2ctl#1]
```
Traceback (most recent call last):
  File "/home/will/git/gstproof/definition_generator.py", line 1, in <module>
    from v4l2ctl import V4l2Device
  File "/home/will/.local/lib/python3.9/site-packages/v4l2ctl/__init__.py", line 25, in <module>
    from .v4l2device import V4l2Device, FeatureNotSupported
  File "/home/will/.local/lib/python3.9/site-packages/v4l2ctl/v4l2device.py", line 17, in <module>
    from .ioctls import V4l2IocOps, V4l2Capabilities, V4l2BufferType, IoctlError
  File "/home/will/.local/lib/python3.9/site-packages/v4l2ctl/ioctls/__init__.py", line 23, in <module>
    from .v4l2ioctlenums import V4l2Formats, V4l2FormatDescFlags, \
  File "/home/will/.local/lib/python3.9/site-packages/v4l2ctl/ioctls/v4l2ioctlenums.py", line 18, in <module>
    from ..utils.enumcontainer import BaseEnumContainer
ModuleNotFoundError: No module named 'v4l2ctl.utils'
```

**Comment by MichaelIsrael** [comment]
Thanks for the feedback.
